canonifyurls = true

hasCJKLanguage = true
summaryLength = 160

disableKinds = ["taxonomy"]

enableEmoji = true
enableRobotsTXT = true

baseurl = "https://takuti.me"
title = "Takuya Kitazawa"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  work = "/work/:contentbasename/"
  note = "/note/:contentbasename/"
  categories = "/note/category/:slug/"
  series = "/:slug/"

[taxonomies]
  category = "categories"
  series = "series"

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    [languages.en.params]
      name = "Takuya Kitazawa"
      keywords = "Takuya Kitazawa,takuti,AI,ML,data,recommender systems,ITIL,Africa,Malawi,Canada,Japan,mentorship,career,tech,consultation,digital inclusion,digital participation,sustainability,digital transformation,ICT4D"
      bio = 'I am an independent consultant, mentor, and advocate for sustainable technology development with a decade of experience in AI/ML products, data systems, and digital transformation. Based in Canada and originally from Japan, I have lived and worked globally, including part-time residence in Malawi, Africa. See <a href="https://takuti.github.io/cv/" target="_blank" rel="noopener">CV <sup><i class="fas fa-external-link-alt"></i></sup></a> for more information, or contact at <b><a href="mailto:hello@takuti.me">hello@takuti.me</a></b>.'
      featured = ["/note/becoming-a-product-manager/", "/note/hivemall-events-2018-autumn/", "/note/parallel-vs-concurrent/"]
      homeDescription = "Takuya Kitazawa - Independent consultant helping organizations bridge the gap between technology design and real-world user needs. Specializing in AI/ML products, data systems, and digital transformation. Based in Ottawa, Canada."
      blogDescription = "Writing about what I think, learned, and experienced. These are the dots yet to be connected."
      disclaimer = "<ul><li>Opinions are my own and do not represent the views of organizations I am/was belonging to.</li><li>I am doing my best to ensure the accuracy and fair use of the information. However, there might be some errors, outdated information, or biased subjective statements because the main purpose of this blog is to jot down my personal thoughts as soon as possible before conducting an extensive investigation. Visitors understand the limitations and rely on any information at their own risk.</li><li>That said, if there is any issue with the content, please contact me so I can take the necessary action.</li></ul>"

  [languages.ja]
    languageName = "日本語"
    weight = 2
    contentDir = "content/ja"
    [languages.ja.params]
      name = "Takuya Kitazawa（たくち）"
      keywords = "Takuya Kitazawa,takuti,たくち,アフリカ,マラウイ,カナダ,AI,機械学習,推薦システム,データサイエンス,コンサルティング,倫理,DX,デジタルトランスフォーメーション"
      bio = '長野県出身、カナダの首都・オタワを拠点に活動するデジタル戦略アドバイザーです。10年以上にわたりB2B/B2Cの各領域でWeb技術・データサイエンス・機械学習のプロダクト化および顧客への導入支援・コンサルティングに携わってきました。現在は独立し、アフリカ・アジア・北米の企業や個人を対象に、テクノロジー戦略の策定・実装をお手伝いしています。<a href="/ja/malawi">アフリカのマラウイ</a>では現地企業のICTディレクターとして、デジタル・トランスフォーメーションを推進。詳しい経歴は<a href="https://takuti.github.io/cv/" target="_blank" rel="noopener">CV <sup><i class="fas fa-external-link-alt"></i></sup></a> を参照ください。ご意見・ご感想およびお仕事のご相談は <b><a href="mailto:hello@takuti.me">hello@takuti.me</a></b> まで。'
      featured = ["/ja/note/two-decades-of-amazon-recommender/", "/ja/note/product-management-myths/", "/ja/note/data-science-project-structure/"]
      homeDescription = "Takuya Kitazawa - 長野県出身、カナダの首都・オタワを拠点に活動するデジタル戦略アドバイザー。AI・データサイエンス・機械学習を専門とし、フリーランスとしてアフリカ・アジア・北米の企業や個人にテクノロジー戦略や技術的支援を提供。アフリカのマラウイではICTディレクターとしてデジタル・トランスフォーメーションを推進。"
      blogDescription = "「生きること」「学ぶこと」「作ること」について綴っています。"
      disclaimer = '<ul><li>Amazonのアソシエイトとして、当サイトは <a href="https://amzn.to/3QZGuBp" target="_blank">amazon.co.jp</a> 上の適格販売により収入を得ています。</li><li>当サイトおよび関連するメディア上での発言はすべて私個人の見解であり、所属する（あるいは過去に所属した）組織のいかなる見解を代表するものでもありません。</li><li>当サイトのコンテンツ・情報につきまして、可能な限り正確な情報を掲載するよう努めておりますが、個人ブログという性質上、誤情報や客観性を欠いた意見が入り込んでいることもございます。いかなる場合でも、当サイトおよびリンク先に掲載された内容によって生じた損害等の一切の責任を負いかねますのでご了承ください。</li><li>その他、記事の内容や掲載画像などに問題がございましたら、直接メールでご連絡ください。確認の後、対応させていただきます。</li></ul>'

[services]
  [services.googleAnalytics]
    id = "G-0JG95XY8EM"

[params]
  author = "Takuya Kitazawa"
  images = ["/images/thumbnail.png", "/images/takuti.jpg"]
